const mongoose = require('mongoose');

// Define the schema for the "reportList" collection
const reportSchema = new mongoose.Schema({

  term: Number,
  name: String,
  class: String,
  DOB: String,
  POB: String,
  enrollment: Number,
  master: String,
  situation: String,
  test1: String,
  test2: String,
  eng1: Number,
  fre1: Number,
  math1: Number,
  hist1: Number,
  lit1: Number,
  geo1: Number,
  econs1: Number,
  comm1: Number,
  acc1: Number,
  citi1: Number,
  rel1: Number,
  food1: Number,
  chem1: Number,
  bio1: Number,
  phy1: Number,
  comp1: Number,
  sport1: Number,
  logic1: Number,
  hb1: Number,
  eng2: Number,
  fre2: Number,
  math2: Number,
  hist2: Number,
  lit2: Number,
  geo2: Number,
  econs2: Number,
  comm2: Number,
  acc2: Number,
  citi2: Number,
  rel2: Number,
  food2: Number,
  chem2: Number,
  bio2: Number,
  phy2: Number,
  comp2: Number,
  sport2: Number,
  logic2: Number,
  hb2: Number,
  average: Number,
  ta: Number,
  na: Number,
  punishment: String,
  DC: String,
  DMC: String,
  AMC: String,
  paid: Number,
  owing: Number,
  summonDate: String,
  summonTime: String,
  note: String,
});

// Create the Mongoose model for the "reportList" collection
const Report = mongoose.model('Report', reportSchema);

module.exports = Report;
